---
dependencies:
   - { role: distributecert }
- name: restart etcd
  service: name=etcd state=restarted
  when: etcd_started.changed == false
- name: restart etcd
  service: name=etcd state=restarted
  when: etcd_started.changed == false
dependencies:
#    - { role: docker }
docker_dependencies:
  - yum-utils
  - lvm2
  - device-mapper-persistent-data

docker_packages:
  - docker-ce
docker_dependencies:
  - yum-utils
  - lvm2
  - device-mapper-persistent-data
dependencies:
#    - { role: docker }
docker_dependencies:
  - yum-utils
  - lvm2
  - device-mapper-persistent-data

docker_packages:
  - docker-ce
docker_dependencies:
  - yum-utils
  - lvm2
  - device-mapper-persistent-data

