---
dependencies:
#    - { role: docker }
docker_packages:
  - docker-ce
docker_dependencies:
  - yum-utils
  - lvm2
  - device-mapper-persistent-data
docker_packages:
  - docker-ce
- name: Install required packages on {{ ansible_distribution }}
  package:
    name: "{{ containerd_packages }}"
    state: latest
docker_dependencies:
  - yum-utils
  - lvm2
  - device-mapper-persistent-data
docker_packages:
  - docker-ce
docker_dependencies:
  - yum-utils
  - lvm2
  - device-mapper-persistent-data
