---
docker_dependencies:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

docker_packages:
  - docker-ce
docker_dependencies:
  - yum-utils
  - lvm2
  - device-mapper-persistent-data

docker_packages:
  - docker-ce
docker_dependencies:
  - yum-utils
  - lvm2
  - device-mapper-persistent-data

docker_packages:
  - docker-ce
