---
- name: Gather OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
  tags: vars

- name: Install Docker dependencies on {{ ansible_distribution }}
  package:
    name: "{{ docker_dependencies }}"
    state: latest
    update_cache: yes

- name: Install Docker repo on CentOS
  command: "yum-config-manager --add-repo {{ docker_repo | default('https://download.docker.com/linux/centos/docker-ce.repo') }}"
  when: ansible_distribution == "CentOS"

- name: Add Docker repo apt signing key on Ubuntu
  apt_key:
    url: "{{ docker_repo_key | default('https://download.docker.com/linux/ubuntu/gpg') }}"
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install Docker repo on Ubuntu
  apt_repository:
    repo: "{{ docker_repo | default('deb [arch=amd64] https://download.docker.com/linux/ubuntu ' + ansible_distribution_release + ' stable') }}"
    state: present
    filename: docker-ce
  when: ansible_distribution == "Ubuntu"

- name: Install Docker on {{ ansible_distribution }}
  package:
    name: "{{ docker_packages }}"
    state: latest
    update_cache: yes

- name: Start Docker Daemon
  service:
    name: docker
    enabled: no
    state: started
    daemon_reload: yes
