---
- name: Create kubernetes addon directory
  file:
    path: "{{ kube_addon_dir }}"
    state: directory
  register: addon_dir

- name: Copy kube-proxy config file
  template:
    src: kube-proxy.yaml.j2
    dest: "{{ kube_addon_dir }}/kube-proxy.yaml"
  when: kube_proxy

- name: Copy flannel config file
  template:
    src: kube-flannel.yaml.j2
    dest: "{{ kube_addon_dir }}/kube-flannel.yaml"
  when: flannel

- name: Copy kube-dns config file
  template:
    src: coredns.yaml.j2
    dest: "{{ kube_addon_dir }}/coredns.yaml"
  when: kube_dns

- name: Copy metrics-server
  template:
    src: metrics-server.yaml.j2
    dest: "{{ kube_addon_dir }}/metrics-server.yaml"
  when: metrics_server

- name: Create kube-proxy
  shell: "kubectl apply --kubeconfig={{ kubeadminconfig }} -f {{ kube_addon_dir }}/kube-proxy.yaml"
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true
  when: kube_proxy

- name: Create kube-flannel
  shell: "kubectl apply --kubeconfig={{ kubeadminconfig }} -f {{ kube_addon_dir }}/kube-flannel.yaml"
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true
  when: flannel

- name: Create kube-dns
  shell: "kubectl apply --kubeconfig={{ kubeadminconfig }} -f {{ kube_addon_dir }}/coredns.yaml"
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true
  when: kube_dns

- name: Create metrics-server
  shell: "kubectl apply --kubeconfig={{ kubeadminconfig }} -f {{ kube_addon_dir }}/metrics-server.yaml"
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true
  when: metrics_server
